# Generated by Django 2.1.7 on 2019-12-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20191217_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contiene',
            name='porcentaje',
            field=models.DecimalField(decimal_places=14, max_digits=14),
        ),
    ]
