# Generated by Django 2.1.7 on 2019-12-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20191217_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contiene',
            name='porcentaje',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
